### PR TITLE
Add support for the AddKeysToAgent key in the config file

### PR DESCRIPTION
**Pull request by bachya**
Adds support for the `AddKeysToAgent` key... At least, I think it does (I'm not a Go expert). Any chance you'd be willing to review? :)

### CODE REVIEW

**Comment by moul** [comment]
Hi @bachya, thank you

I can handle the last few steps, your PR is already really helpful

**Comment by moul** [comment]
I just fixed a typo making tests fail + added an entry in the changelog in #210

**Comment by moul** [comment]
#212 is merged with your commit; thank you!

**Comment by bachya** [comment]
Awesome, thank you!

**Pull request closed without merging**
